name: spyder-py-37
channels:
  - conda-forge
dependencies:
  - python=3.7.9
  - spyder
  - spyder-kernels
  - pandas
  - openpyxl
  - matplotlib
  - seaborn
  - jupyter
  - black
  - isort 
  - flake8

